kind: pipeline
name: default

clone:
  depth: 50


steps:
- name: interface
  image: docker
  environment:
    API_URL: 
      from_secret: API_URL
    DOCKER_REPO: 
      from_secret: docker_repo
    DOCKER_USERNAME: 
      from_secret: docker_username
    DOCKER_PASSWORD: 
      from_secret: docker_password
    DOCKER_REGISTRY: 
      from_secret: docker_registry
  commands:
  - echo $DOCKER_USERNAME
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD $DOCKER_REGISTRY
  - docker build --build-arg API_URL=$API_URL -t interface:latest . 
  - docker tag interface:latest $DOCKER_REGISTRY/interface:latest
  - docker push $DOCKER_REGISTRY/interface:latest    
  branches:
  - devops 
  - master
  volumes:
  - name: docker
    path: /var/run/docker.sock

- name: ssh
  image: appleboy/drone-ssh
  settings: 
    host: curriculo.jurema.la
    username: 
      from_secret: SSH_USERNAME
    port: 22
    key: 
      from_secret: SSH_KEY

volumes:
- name: docker
  host:
    path: /var/run/docker.sock