kind: pipeline
name: default

clone:
  depth: 50


steps:
- name: interface
  image: plugins/docker

  settings:
    build_args_from_env: [ API_URL ]
    build_args:
      - APP_ENV=production
    repo: 
      from_secret: docker_repo
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password 
    registry: 
      from_secret: docker_registry
    
  branches:
  - devops
  - master

