kind: pipeline
name: default

clone:
  depth: 50


steps:
- name: interface
  image: docker
  environment:
    API_URL: 
      from_secret: API_URL
    DOCKER_REPO: 
      from_secret: docker_repo
    DOCKER_USERNAME: 
      from_secret: docker_username
    DOCKER_PASSWORD: 
      from_secret: docker_password
    DOCKER_REGISTRY: 
      from_secret: docker_registry
  commands:
  - echo $DOCKER_USERNAME
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD $DOCKER_REGISTRY
  - docker push $DOCKER_REGISTRY/$DOCKER_REPO

      
  branches:
  - devops
  - master

