kind: pipeline
name: default

clone:
  depth: 50


steps:
- name: interface
  image: plugins/docker
  build_args:
      APP_ENV: production
      API_URL: 
          from_secret: api_url
  settings:
    repo: 
      from_secret: docker_repo
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password 
    registry: 
      from_secret: docker_registry
  branches:
  - devops


